### ISSUE TITLE
OPINION: ideas para agregar

### ISSUE THREAD

**Issue by LautaroDevcpp** [pdepjuevesTT/2024-presentacion-lifern34#1]
Te dejo un comentario para que tu presentación sea un poco más completa. Podrías agregar tu edad, en qué zona vivís, año de la carrera , tus lenguajes favoritos (si es que tenés), etc. Espero te sea de inspiración en caso de que la necesites. Cabe aclarar que el amigo de la foto está muy fachero!

Un saludo!

**Comment by lifern34** [comment]
Excelente idea, la verdad es que sí, la presentación había quedado bastante escasa de información. Ya me pongo a hacer esos cambios y muchas gracias por el aporte y el halago a mi compañero perruno jajajajaj.

Saludos!
